[module.hugoVersion]
extended = true
min = "0.110.0"

[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[params.hb.header]
breakpoint = "lg"
sticky = true
full_width = true
# brand = ""
# brand_url = "" # use a custom brand URL.
