[[module.imports]]
path = "github.com/hbstack/header"

[params.hb.header.theme_toggle]
style = "switch"

[params.hugopress.modules.hb-header-theme-toggle.attributes.document]
cacheable = true

[params.hugopress.modules.hb-header-theme-toggle.hooks.hb-header-panel]
cacheable = true
partial = "hb/modules/header-theme-toggle/index"
