[[module.imports]]
path = "github.com/hbstack/header"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[params.hugopress.modules.hb-header-apps.hooks.hb-header-panel]
cacheable = true
partial = "hb/modules/header-apps/index"
