[[module.imports]]
path = "github.com/hbstack/header"

[params.hugopress.modules.hb-header-gcse.hooks.body-end]
cacheable = true

[params.hugopress.modules.hb-header-gcse.hooks.hb-header-togglers-begin]
cacheable = true
partial = "hb/modules/header-gcse/index"

[params.hb.header.gcse]
id = ""
layout = ""
