[[module.imports]]
path = "github.com/hbstack/header"

[params.hugopress.modules.hb-header-news.hooks.hb-header-panel]
weight = 10

[params.hb.header.news]
sections = ["news"]
limit = 5
date_format = ":date_full"
icon_name = "bell" # Use anohter Bootstrap icon, e.g. megaphone.
icon_vendor = "bootstrap" # Use icons vendor other than Bootstrap.
