[[module.imports]]
path = "github.com/hbstack/header"

[params.hugopress.modules.hb-header-news.hooks.hb-header-panel]

[params.hb.header.news]
sections = ["news"]
limit = 5
date_format = ":date_full"
