[[module.imports]]
path = "github.com/hbstack/header"

[[module.imports]]
path = "github.com/hbstack/search"

[params.hugopress.modules.hb-header-search.hooks.hb-header-togglers-begin]
cacheable = true
partial = "hb/modules/header-search/index"
